---
title: Replication of The Link Between Self-Dehumanization and Immoral Behavior by
  Kouchaki, Dobson, Waytz, & Kteily (2018, Psychological Science)
author: "Nicky Sullivan (nsull13@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

###Justification for Choice of Experiment

My research interests broadly cover how children learn about and conceptualize social categories, but due to the time limitations working with adults seems significantly more manageable. This study looks at dehumanization in adults, which is closely tied to adults' broader conceptions of social categories. 

###Paper Description

This paper is composed of 3 studies (2 of which are broken down into sub-studies) that broadly look at the links between self-dehumanization and immoral behavior. I will be replicating Study 1a, which tests whether thinking about past unethical behavior will lead to self-dehumanization.

Participants are recruited from Mechanical Turk. They start by recalling an event from the past (either ethical, unethical, or neutral depending on condition) and writing about it. They then complete a 10-item self-dehumanization scale based on the Mind Attribution Scale. There are also two attention checks: one that asks participants to report what topic they were supposed to write about and one as part of the self-dehumanization scale that simply asks them to select "3". Participants will also complete a brief demographic questionnaire.

###Stimuli Required

-Writing prompt
-Self-dehumanization scale (10 items)
-Attention check questions (2 items)
-Demographic questionnaire

###Challenges

The main challenge will be getting a sample size that is large enough given limited constraints, especially after removing any participants that will be excluded based on the attention checks. 

###Links

Project repository: https://github.com/psych251/kouchaki2018.git
Original paper: 

##Methods

###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

###Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

###Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
